CREATE TABLE member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    displayName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE board (
    boardId BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    memberId BIGINT,
    FOREIGN KEY (memberId) REFERENCES member(id)
);